language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

before_install:
  - pip install codecov

install:
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install Django==${DJANGO}

script: coverage run --source appgen runtests.py

env:
  - DJANGO=1.8.7
  - DJANGO=1.9

matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.9
    - python: 3.5
      env: DJANGO=1.8.7

after_success:
  - codecov
